---

- name: install anydesk apt key
  become: yes
  apt_key:
    url: 'https://keys.anydesk.com/repos/DEB-GPG-KEY'
    state: present

- name: install anydesk repo
  become: yes
  apt_repository:
    repo: deb http://deb.anydesk.com/ all main
    filename: anydesk-stable
    state: present

- name: install anydesk
  become: yes
  apt:
    name: anydesk
    state: present
