---
#   - include_tasks: vscode.yml
#   - include_tasks: docker.yml
#   - include_tasks: chrome.yml
#   - include_tasks: anydesk.yml
#   - include_tasks: keepass2.yml
#   - include_tasks: syncthing.yml
#   - include_tasks: inkscape.yml
#   - include_tasks: veracrypt.yml
  - include_tasks: vpn.yml
#   - include_tasks: flatpak.yml
#   - include_tasks: telegram.yml
#   - include_tasks: spotify.yml
#   - include_tasks: obsidian.yml
#   - include_tasks: krita.yml
#   - include_tasks: _bash_customizations.yml
#   - include_tasks: _gnome_customizations.yml
#   - include_tasks: _git_indentity.yml
