---

- name: install syncthing apt key
  become: yes
  apt_key:
    url: 'https://syncthing.net/release-key.txt'
    state: present

- name: install syncthing repo
  become: yes
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing release
    filename: syncthing
    state: present

- name: install syncthing
  become: yes
  apt:
    name: syncthing
    state: present
