---

- name: install syncthing apt key
  become: yes
  apt_key:
    url: 'https://syncthing.net/release-key.txt'
    state: present

- name: install syncthing repo
  become: yes
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing release
    filename: syncthing
    state: present

- name: install syncthing
  become: yes
  apt:
    name: syncthing
    state: present

- name: create service folders
  ansible.builtin.file:
    path: '~/.config/systemd/user/'
    state: directory

- name: create service config
  copy:
    src: /usr/lib/systemd/system/syncthing@.service 
    dest: '~/.config/systemd/user/syncthing@{{ ansible_env.USER }}.service'

- name: make sure syncthing is started and enabled
  become: yes
  systemd:
    name: 'syncthing@{{ ansible_env.USER }}.service'
    state: started
    enabled: true