---

- name: install virtualbox apt key
  become: yes
  apt_key:
    url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'
    state: present

- name: install virtualbox repo
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian focal contrib
    filename: virtualbox
    state: present

- name: install virtualbox
  become: yes
  apt:
    name: virtualbox-6.0
    state: present
